spring.application.name=bankingApp
server.port=6767
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingData
spring.datasource.username=bankAppAdmin
spring.datasource.password=securelyBanked

#Turns off SpringBoot Banner
spring.main.banner-mode=OFF
logging.level.root=warn

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Add logging configs to display SQL statements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace


#Bank Details
bank.routing-number = 91000019